### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by DzikiOwoc15** [DzikiOwoc15/markdown#1]
### Tabelka {#id1}
|  KOLUMNA 1| KOLUMNA 2| KOLUMNA 3|
| :-------------:|:-------------:|:-------------:|
| wartosc 1     | wartosc 2    | wartosc 3      |

### kodzik {#id2}
```python
for x in bomba:
    print(x)
```

### footer {#id3}
tu jest stopka[^1]

[^1]: to jest stopka

:shit: :+1:
### todo {#id4}
- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media

I need to highlight these ==very important words==.
